# Screen
SCREEN_REFRESH_RATE = 0.1
SCREEN_WIDTH = 620
SCREEN_HEIGHT = 640
SCOREBOARD_HEIGHT = 290

# Game area
LEFT_LIMIT = -280
RIGHT_LIMIT = 280
TOP_LIMIT = 280
BOTTOM_LIMIT = -280

# Snake movement
MOVE_DISTANCE = 20

# Directions
UP_DEGREES, UP_TEXT = (90, "Up")
DOWN_DEGREES, DOWN_TEXT = (270, "Down")
LEFT_DEGREES, LEFT_TEXT = (180, "Left")
RIGHT_DEGREES, RIGHT_TEXT = (0, "Right")
